name: Build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v4
        with:
          node-version: 20.9.0
          cache: npm

      - name: Install JS dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Commit and push distified version to master
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'Update distified version'
          file_pattern: 'dist/index.js'
          commit_options: '--allow-empty'
